init = (urls) ->
    urls.update({
        "auth": "/api/v1/auth"
        "auth-register": "/api/v1/auth/register"
        "permissions": "/api/v1/permissions"
        "roles": "/api/v1/roles"
        "projects": "/api/v1/projects"
        "memberships": "/api/v1/memberships"
        "milestones": "/api/v1/milestones"
        "userstories": "/api/v1/userstories"
        "bulk-create-us": "/api/v1/userstories/bulk_create"
        "bulk-update-us-order": "/api/v1/userstories/bulk_update_order"
        "userstories-restore": "/api/v1/userstories/%s/restore"
        "tasks": "/api/v1/tasks"
        "bulk-create-tasks": "/api/v1/tasks/bulk_create"
        "tasks-restore": "/api/v1/tasks/%s/restore"
        "issues": "/api/v1/issues"
        "issues-restore": "/api/v1/issues/%s/restore"
        "wiki": "/api/v1/wiki"
        "wiki-restore": "/api/v1/wiki/%s/restore"
        "choices/userstory-statuses": "/api/v1/userstory-statuses"
        "choices/userstory-statuses/bulk-update-order": "/api/v1/userstory-statuses/bulk_update_order"
        "choices/points": "/api/v1/points"
        "choices/points/bulk-update-order": "/api/v1/points/bulk_update_order"
        "choices/task-statuses": "/api/v1/task-statuses"
        "choices/task-statuses/bulk-update-order": "/api/v1/task-statuses/bulk_update_order"
        "choices/issue-statuses": "/api/v1/issue-statuses"
        "choices/issue-statuses/bulk-update-order": "/api/v1/issue-statuses/bulk_update_order"
        "choices/issue-types": "/api/v1/issue-types"
        "choices/issue-types/bulk-update-order": "/api/v1/issue-types/bulk_update_order"
        "choices/priorities": "/api/v1/priorities"
        "choices/priorities/bulk-update-order": "/api/v1/priorities/bulk_update_order"
        "choices/severities": "/api/v1/severities"
        "choices/severities/bulk-update-order": "/api/v1/severities/bulk_update_order"
        "search": "/api/v1/search"
        "sites": "/api/v1/sites"
        "project-templates": "/api/v1/project-templates"
        "site-members": "/api/v1/site-members"
        "site-projects": "/api/v1/site-projects"
        "users": "/api/v1/users"
        "users-password-recovery": "/api/v1/users/password_recovery"
        "users-change-password-from-recovery": "/api/v1/users/change_password_from_recovery"
        "users-change-password": "/api/v1/users/change_password"
        "resolver": "/api/v1/resolver"
        "wiki-attachment": "/media/attachment-files/%s/wikipage/%s"

        # History
        "history/userstory": "/api/v1/history/userstory"
        "history/issue": "/api/v1/history/issue"
        "history/task": "/api/v1/history/task"
        "history/wiki": "/api/v1/history/wiki"

        # Attachments
        "userstories/attachments": "/api/v1/userstories/attachments"
        "issues/attachments": "/api/v1/issues/attachments"
        "tasks/attachments": "/api/v1/tasks/attachments"
        "wiki/attachments": "/api/v1/wiki/attachments"
    })

module = angular.module("taigaResources", [])
module.run(["$tgUrls", init])
